version: '3'

services:
  # to enable the management plugin (web)
  # docker exec fz_rabbitmq rabbitmq-plugins enable rabbitmq_management
  rabbitmq:
    hostname: fz_rabbitmq
    container_name: fz_rabbitmq
    image: rabbitmq:alpine
    environment:
      - RABBITMQ_DEFAULT_USER=root
      - RABBITMQ_DEFAULT_PASS=root
      - RABBITMQ_ERLANG_COOKIE=fzcookie
    ports:
      - "10001:15672"
      - "10002:5672"

  webserver:
    container_name: fz_webserver
    image: fz/webserver:latest
    environment:
      - AURELIALOCATION=/opt/aurelia
      - SSLPATH=/opt/shiro/self.keystore
      - SSLPASS=some-password
    build:
      context: .
      dockerfile: ./.docker/webserver/file.dockerfile
    ports:
      - "9080:8880"
      - "9443:8443"

  apigateway:
    container_name: fz_apigateway
    image: fz/apigateway:latest
    environment:
      - RABBIT_HOST=fz_rabbitmq
      - RABBIT_USER=root
      - RABBIT_PASS=root
      - RABBIT_PORT=10002
      - DOMAIN=localhost
      - REMEMBERME=Tzhfrprwksieaxxw
      - HASHSERVICE=LnnjousalfizuleiPsiyzzwpelvbnfpo
      - SESSIONDURATION=3600000
      - SSLPATH=/opt/shiro/self.keystore
      - SSLPASS=some-password
      - CORS=*
    build:
      context: .
      dockerfile: ./.docker/apigateway/file.dockerfile
    ports:
      - "8089:8089"
      - "8090:8090"

  members:
    container_name: fz_members
    image: fz/members:latest
    environment:
      - RABBIT_HOST=fz_rabbitmq
      - RABBIT_USER=root
      - RABBIT_PASS=root
      - RABBIT_PORT=10002
      - HASHSERVICE=LnnjousalfizuleiPsiyzzwpelvbnfpo
    build:
      context: .
      dockerfile: ./.docker/members/file.dockerfile


